//
//  InfoView.swift
//  HeadBoyAdviceApp
//
//  Created by Ben Freeman on 2021-03-11.
//

import SwiftUI

struct InfoView: View {
    var body: some View {
        ScrollView {

                    Text("Sample Textasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhfextasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhfextasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhfextasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhfextasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhfextasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhfextasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhfextasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhf Kevin penkin extasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhfextasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhfextasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhfextasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhfextasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhfextasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhfextasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhfextasdfasdfasdfasdfalsdkfjhlkjhasdlkjhasdlkjhsdkjhadkjhasldkfjhalskdjfhalksdjhfalsdkjhfalsdjfhlksdjhfalksdjhf david dobs")
        .padding([.bottom, .trailing])
        }
        
    }
}

struct InfoView_Previews: PreviewProvider {
    static var previews: some View {
        InfoView()
    }
}
